---
- name: Install and Start Nginx
  hosts: dev
  remote_user: ansible
  become: yes
  connection: ssh
  gather_facts: no

  tasks:
    - name: Update package list
      command: apt update

    - name: Install nginx
      command: apt install nginx -y

    - name: Start nginx service
      command: systemctl start nginx

    - name: Enable nginx on boot
      command: systemctl enable nginx